### ISSUE TITLE
finne fargekodene og dimensjonene til Sverige

### ISSUE THREAD

**Issue by martinsteiro** [Orhanyil/Gruppe_12B#24]

**Comment by Orhanyil** [comment]
fullført

**Comment by martinsteiro** [comment]
Har vi riktige dimensjoner?

**Comment by Orhanyil** [comment]
Ja,

26 Eyl 2022 Pzt 15:18 tarihinde martinsteiro ***@***.***>
şunu yazdı:

**Comment by Orhanyil** [comment]
Det gjeder sverige flaggs lov

26 Eyl 2022 Pzt 15:19 tarihinde Orhan Yildirim ***@***.***>
şunu yazdı:

**Comment by Orhanyil** [comment]
Sveriges nasjonalflagg skal være i forholdet 10/16 (høyde / lengde). De
indre (nærmest flaggstangen) blå feltene skal være i forholdet 4/5 (høyde /
lengde), og de ytre feltene 4/9 (høyde / lengde). Korsets bredde skal være
halvparten av de blå feltenes høyde

26 Eyl 2022 Pzt 15:19 tarihinde Orhan Yildirim ***@***.***>
şunu yazdı:
